CREATE OR REPLACE PACKAGE C_PACKAGE AS
 -- Adds a customer
    PROCEDURE ADDCUSTOMER(
        C_ID CUSTOMERS.ID%TYPE,
        C_NAME CUSTOMERS.NAME%TYPE,
        C_AGE CUSTOMERS.AGE%TYPE,
        C_ADDR CUSTOMERS.ADDRESS%TYPE,
        C_SAL CUSTOMERS.SALARY%TYPE
    );
 -- Removes a customer
    PROCEDURE DELCUSTOMER(
        C_ID CUSTOMERS.ID%TYPE
    );
 --Lists all customers
    PROCEDURE LISTCUSTOMER;
END C_PACKAGE;
/